### ISSUE TITLE
Error in code in class.cpp

### ISSUE THREAD

**Issue by SachinSahu431** [MathewKJ2048/Minesweeper#10]
Replace [line 55](https://github.com/MathewKJ2048/Minesweeper/blob/01a79b4933583ebeec2555e248fe9f1b032d3968/class.cpp#L55) with this:	 if(is_q_marked[i][j]){q_mark[i][j]=false;}

https://github.com/MathewKJ2048/Minesweeper/blob/01a79b4933583ebeec2555e248fe9f1b032d3968/class.cpp#L55

**Comment by MathewKJ2048** [comment]
done

**Comment by SachinSahu431** [comment]
cool!
