### ISSUE TITLE
Delete branch "MathewKJ2048-skeleton"

### ISSUE THREAD

**Issue by SachinSahu431** [MathewKJ2048/Minesweeper#6]
**MathewKJ2048-skeleton** brach can be deleted as we have updated it to **MathewKJ2048-skeleton-15** branch.

**Comment by MathewKJ2048** [comment]
yes. I did not know how to edit a pull request so I made a new one. Now I know, so I wont have to

**Comment by SachinSahu431** [comment]
Okay
