### ISSUE TITLE
set_mines functionality

### ISSUE THREAD

**Issue by sirish123** [MathewKJ2048/Minesweeper#7]
I have written the set mines function ,can someone pls review and see what else must be added( set_mines branch)
1.The problem of allocation of the specified number of bombs is solved.
2.A separate array has been created keeping track of bombs and its surrounding
  a.-1 indicates bomb
  b.1 indicates tiles surrounding the bombs within 8 square vicinity
  c.0 indicates those tiles not present within 8 square vicinity of any mine

whoever is using setmines function pls do verify and see what functionaility is required

**Comment by MathewKJ2048** [comment]
Ok il review

**Comment by MathewKJ2048** [comment]
Is it in the closed branch?

**Comment by sirish123** [comment]
setmines new branch

**Comment by sirish123** [comment]
https://github.com/MathewKJ2048/Minesweeper/tree/set_mine-branch

**Comment by MathewKJ2048** [comment]
Here is what is required:
1)a single function called void set_field(int i,int j) which sets both mines and numbers
2)It has full access to the global arrays so creation of new arrays inside it is not necessary
3)the number of mines it needs to lay is a global variable and not passed as an argument
4)the only arguments it needs to take are the coordinates of which box to avoid
5)protocode1 in branch has has some of the logic necessary

**Comment by sirish123** [comment]
apart from the global and local problems ,does the function cater to its needs?

**Comment by MathewKJ2048** [comment]
I think it does. Now that skeleton is comitted to main branch, you can make edits to that directly

**Comment by MathewKJ2048** [comment]
Once you write the function as a part of skeleton, start a pull request. further discussion can be carried out there
